### ISSUE TITLE
option to have civet ignore files in certain directories

### ISSUE THREAD

**Issue by aristretto** [counsyl/civet#3]
Hey @lukhnos!

I've come across what I believe to be a pretty common scenario that trips up Civet.

Bower packages often have two main sets of files, distribution and source.

- distribution files are ready-to-go out of the box.  they generally require no config or compilation.
- source files are often included so developers can peek under-the-hood, or make changes ad-hoc.
  - these often come with some kind of build system.

Source files can sometimes be multi-lingual if a build system is involved.  Build scripts can perform variable replacements before a compiler processes a file, which means that if said files were run through a compiler *before* a build system performed var replacements the compiler would likely encounter syntax errors.

One such case is Font-Awesome.  Civet looks for files with `.scss` or `.sass` file extensions.  In https://github.com/FortAwesome/Font-Awesome/blob/master/src/assets/font-awesome/scss/font-awesome.scss#L3 we see non-standard Sass syntax (likely replaced by some build script pre compilation).

Civet will look at this file and try to compile it, but shouldn't.

Is there a way to tell Civet not to look at certain directories such as `bower_components` or `node_modules`?  Imagine for the sake of this scenario that we cannot simply move these directories elsewhere.

**Comment by lukhnos** [comment]
@aristretto I think this is solved by https://github.com/counsyl/civet/pull/5 ?
